version: '3'

tasks:
  ci:
    desc: Run CI pipeline (build and test all)
    cmds:
      - task: build
      - task: test-all
        
        
  restore:
    desc: Restore .NET dependencies
    cmds:
      - dotnet restore Lerevently.slnx

  build:
    desc: Build the solution
    deps: [ restore ]
    cmds:
      - dotnet build Lerevently.slnx --no-restore --configuration Release

  test-all:
    desc: Run all tests in parallel
    deps: [ test-users, test-ticketing, test-events, test-attendance, test-modules-architecture ]

  test-users:
    desc: Run tests for Users module
    deps: [build]
    cmds:
      - dotnet run --project Lerevently.Modules.Users.ArchitectureTests/Lerevently.Modules.Users.ArchitectureTests.csproj --configuration Release --no-build -- --report-trx --report-trx-filename users-architecture-tests.trx --results-directory ./TestResults/UsersArchitecture

  test-ticketing:
    desc: Run tests for Ticketing module
    deps: [build]
    cmds:
      - dotnet run --project Lerevently.Modules.Ticketing.ArchitectureTests/Lerevently.Modules.Ticketing.ArchitectureTests.csproj --configuration Release --no-build -- --report-trx --report-trx-filename ticketing-architecture-tests.trx --results-directory ./TestResults/TicketingArchitecture

  test-events:
    desc: Run tests for Events module
    deps: [build]
    cmds:
      - dotnet run --project Lerevently.Modules.Events.ArchitectureTests/Lerevently.Modules.Events.ArchitectureTests.csproj --configuration Release --no-build -- --report-trx --report-trx-filename events-architecture-tests.trx --results-directory ./TestResults/EventsArchitecture

  test-attendance:
    desc: Run tests for Attendance module
    deps: [build]
    cmds:
      - dotnet run --project Lerevently.Modules.Attendance.ArchitectureTests/Lerevently.Modules.Attendance.ArchitectureTests.csproj --configuration Release --no-build -- --report-trx --report-trx-filename attendance-architecture-tests.trx --results-directory ./TestResults/AttendanceArchitecture

  test-modules-architecture:
    desc: Run architecture tests (standalone)
    deps: [build]
    cmds:
      - dotnet run --project Lerevently.ArchitectureTests/Lerevently.ArchitectureTests.csproj --configuration Release --no-build -- --report-trx --report-trx-filename architecture-tests.trx --results-directory ./TestResults/Architecture
